python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000009.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000010.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000011.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000012.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000013.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000014.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000015.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000016.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000017.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000018.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000019.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000020.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000021.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000023.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000024.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000025.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/LES_Injection_Turbulent/all/LES_02/cm1out_rst_000026.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/les_injection_turbulent/all/LES_02/cm1out_rst_000027.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/les_injection_turbulent/all/LES_02/cm1out_rst_000028.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/les_injection_turbulent/all/LES_02/cm1out_rst_000029.nc &
python idealConvObs.py /scratch/jonathan.labriola/idealized/250m/les_injection_turbulent/all/LES_02/cm1out_rst_000030.nc &
wait
